package Pojo;
// Generated Mar 20, 2015 7:49:03 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private Integer idCourse;
     private Department department;
     private String name;
     private String description;
     private int isActive;
     private Set labs = new HashSet(0);
     private Set groups = new HashSet(0);

    public Course() {
    }

	
    public Course(Department department, String name, String description, int isActive) {
        this.department = department;
        this.name = name;
        this.description = description;
        this.isActive = isActive;
    }
    public Course(Department department, String name, String description, int isActive, Set labs, Set groups) {
       this.department = department;
       this.name = name;
       this.description = description;
       this.isActive = isActive;
       this.labs = labs;
       this.groups = groups;
    }
   
    public Integer getIdCourse() {
        return this.idCourse;
    }
    
    public void setIdCourse(Integer idCourse) {
        this.idCourse = idCourse;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }
    public Set getLabs() {
        return this.labs;
    }
    
    public void setLabs(Set labs) {
        this.labs = labs;
    }
    public Set getGroups() {
        return this.groups;
    }
    
    public void setGroups(Set groups) {
        this.groups = groups;
    }




}


