package Pojo;
// Generated Mar 20, 2015 7:49:03 PM by Hibernate Tools 3.6.0



/**
 * Trainee generated by hbm2java
 */
public class Trainee  implements java.io.Serializable {


     private Integer idTrainee;
     private User user;
     private int intake;

    public Trainee() {
    }

    public Trainee(User user, int intake) {
       this.user = user;
       this.intake = intake;
    }
   
    public Integer getIdTrainee() {
        return this.idTrainee;
    }
    
    public void setIdTrainee(Integer idTrainee) {
        this.idTrainee = idTrainee;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getIntake() {
        return this.intake;
    }
    
    public void setIntake(int intake) {
        this.intake = intake;
    }




}


