package Pojo;
// Generated Mar 20, 2015 7:49:03 PM by Hibernate Tools 3.6.0



/**
 * UserNotifications generated by hbm2java
 */
public class UserNotifications  implements java.io.Serializable {


     private UserNotificationsId id;
     private User userByUserRecieverId;
     private User userByUserSenderId;
     private String message;

    public UserNotifications() {
    }

    public UserNotifications(UserNotificationsId id, User userByUserRecieverId, User userByUserSenderId, String message) {
       this.id = id;
       this.userByUserRecieverId = userByUserRecieverId;
       this.userByUserSenderId = userByUserSenderId;
       this.message = message;
    }
   
    public UserNotificationsId getId() {
        return this.id;
    }
    
    public void setId(UserNotificationsId id) {
        this.id = id;
    }
    public User getUserByUserRecieverId() {
        return this.userByUserRecieverId;
    }
    
    public void setUserByUserRecieverId(User userByUserRecieverId) {
        this.userByUserRecieverId = userByUserRecieverId;
    }
    public User getUserByUserSenderId() {
        return this.userByUserSenderId;
    }
    
    public void setUserByUserSenderId(User userByUserSenderId) {
        this.userByUserSenderId = userByUserSenderId;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


