package Pojo;
// Generated Mar 20, 2015 7:49:03 PM by Hibernate Tools 3.6.0



/**
 * UserPhones generated by hbm2java
 */
public class UserPhones  implements java.io.Serializable {


     private Integer userId;
     private String phone;

    public UserPhones() {
    }

    public UserPhones(String phone) {
       this.phone = phone;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


