package Pojo;
// Generated Mar 20, 2015 7:49:03 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * UsersDelivery generated by hbm2java
 */
public class UsersDelivery  implements java.io.Serializable {


     private UsersDeliveryId id;
     private User user;
     private Lab lab;
     private Date toWhenDate;

    public UsersDelivery() {
    }

	
    public UsersDelivery(UsersDeliveryId id, User user, Lab lab) {
        this.id = id;
        this.user = user;
        this.lab = lab;
    }
    public UsersDelivery(UsersDeliveryId id, User user, Lab lab, Date toWhenDate) {
       this.id = id;
       this.user = user;
       this.lab = lab;
       this.toWhenDate = toWhenDate;
    }
   
    public UsersDeliveryId getId() {
        return this.id;
    }
    
    public void setId(UsersDeliveryId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Lab getLab() {
        return this.lab;
    }
    
    public void setLab(Lab lab) {
        this.lab = lab;
    }
    public Date getToWhenDate() {
        return this.toWhenDate;
    }
    
    public void setToWhenDate(Date toWhenDate) {
        this.toWhenDate = toWhenDate;
    }




}


