package Pojo;
// Generated Mar 19, 2015 8:46:14 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private Department department;
     private String email;
     private String pass;
     private String name;
     private int isActive;
     private Set groups = new HashSet(0);
     private Set labs = new HashSet(0);
     private Set trainees = new HashSet(0);
     private Set userNotificationsesForUserRecieverId = new HashSet(0);
     private Set userNotificationsesForUserSenderId = new HashSet(0);
     private Set usersDeliveries = new HashSet(0);
     private Set staffs = new HashSet(0);

    public User() {
    }

	
    public User(Department department, String email, String pass, String name, int isActive) {
        this.department = department;
        this.email = email;
        this.pass = pass;
        this.name = name;
        this.isActive = isActive;
    }
    public User(Department department, String email, String pass, String name, int isActive, Set groups, Set labs, Set trainees, Set userNotificationsesForUserRecieverId, Set userNotificationsesForUserSenderId, Set usersDeliveries, Set staffs) {
       this.department = department;
       this.email = email;
       this.pass = pass;
       this.name = name;
       this.isActive = isActive;
       this.groups = groups;
       this.labs = labs;
       this.trainees = trainees;
       this.userNotificationsesForUserRecieverId = userNotificationsesForUserRecieverId;
       this.userNotificationsesForUserSenderId = userNotificationsesForUserSenderId;
       this.usersDeliveries = usersDeliveries;
       this.staffs = staffs;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }
    public Set getGroups() {
        return this.groups;
    }
    
    public void setGroups(Set groups) {
        this.groups = groups;
    }
    public Set getLabs() {
        return this.labs;
    }
    
    public void setLabs(Set labs) {
        this.labs = labs;
    }
    public Set getTrainees() {
        return this.trainees;
    }
    
    public void setTrainees(Set trainees) {
        this.trainees = trainees;
    }
    public Set getUserNotificationsesForUserRecieverId() {
        return this.userNotificationsesForUserRecieverId;
    }
    
    public void setUserNotificationsesForUserRecieverId(Set userNotificationsesForUserRecieverId) {
        this.userNotificationsesForUserRecieverId = userNotificationsesForUserRecieverId;
    }
    public Set getUserNotificationsesForUserSenderId() {
        return this.userNotificationsesForUserSenderId;
    }
    
    public void setUserNotificationsesForUserSenderId(Set userNotificationsesForUserSenderId) {
        this.userNotificationsesForUserSenderId = userNotificationsesForUserSenderId;
    }
    public Set getUsersDeliveries() {
        return this.usersDeliveries;
    }
    
    public void setUsersDeliveries(Set usersDeliveries) {
        this.usersDeliveries = usersDeliveries;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }




}


